# Generated by Django 3.0.4 on 2020-03-25 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('content', models.CharField(max_length=400, null=True)),
                ('noteType', models.CharField(choices=[('healthLog', 'healthLog'), ('log', 'log'), ('user', 'user')], default='log', max_length=10)),
            ],
        ),
    ]
