# Generated by Django 3.0.4 on 2020-04-15 09:56

import datetime
from django.db import migrations, models
import django.utils.timezone
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, validators=[user.validators.validate_username])),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('last_access', models.DateField(default=datetime.date.today)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateField(default=datetime.date.today)),
                ('user_type', models.IntegerField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_entity',
            },
        ),
    ]
