# Generated by Django 3.0.4 on 2020-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'admin'), (100, 'monitor'), (200, 'atRisk'), (201, 'helper'), (256, 'unspecified')], db_column='userType', null=True),
        ),
    ]
