# Generated by Django 3.0.4 on 2020-04-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20200416_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthlog',
            name='patient_id',
            field=models.OneToOneField(db_column='userId', limit_choices_to={'user_type__in': (201, 200)}, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'admin'), (100, 'monitor'), (200, 'atRisk'), (201, 'helper'), (25, 'unspecified')], db_column='userType', default=25),
        ),
    ]
