"""
Django settings for django_server project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
<<<<<<< HEAD
SECRET_KEY = 'ld5a8j)tm3at5yz5h-d(s++)*f#v9*8p41w+d4m59h#n%3p*l='
=======
SECRET_KEY = 'ld5a8j)tm3at5yz5h-d(s++)f#v98p41w+d4m59h#n%3p*l='
>>>>>>> 60c466ca4330c47292fdb03c3abb89d7cee3d3bf
=======
SECRET_KEY = 'ld5a8j)tm3at5yz5h-d(s++)f#v98p41w+d4m59h#n%3p*l='
>>>>>>> 94ece97c71f1c4a76841098d8df9ed9ffa442034

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

<<<<<<< HEAD
<<<<<<< HEAD
=======
AUTH_USER_MODEL = 'user.MyUser'
>>>>>>> 60c466ca4330c47292fdb03c3abb89d7cee3d3bf
=======
AUTH_USER_MODEL = 'test_app.MyUser'

>>>>>>> 94ece97c71f1c4a76841098d8df9ed9ffa442034

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
	  'drf_yasg',
    'test_app',
<<<<<<< HEAD
<<<<<<< HEAD
=======
    'drf_generators',
    'user'
>>>>>>> 60c466ca4330c47292fdb03c3abb89d7cee3d3bf
=======
    'drf_generators'
>>>>>>> 94ece97c71f1c4a76841098d8df9ed9ffa442034
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
<<<<<<< HEAD
<<<<<<< HEAD
        'NAME': 'hh_db',
=======
        'NAME': 'hh_unstable',    # to test locally using an empty db
>>>>>>> 60c466ca4330c47292fdb03c3abb89d7cee3d3bf
=======
        'NAME': 'unstable_integration',    # to test locally using an empty db
>>>>>>> 94ece97c71f1c4a76841098d8df9ed9ffa442034
        'USER': 'root',
        'PASSWORD': '',
    }
}

<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 94ece97c71f1c4a76841098d8df9ed9ffa442034
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

<<<<<<< HEAD
>>>>>>> 60c466ca4330c47292fdb03c3abb89d7cee3d3bf
=======
SIMPLE_JWT = {
    'USER_ID_FIELD': 'user_id'
}
>>>>>>> 94ece97c71f1c4a76841098d8df9ed9ffa442034

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
